name: Release images

on:
  push:
    branches: [ master ]
    tags: ['*']

jobs:
  Integration:
    uses: enspirit/talktome/.github/workflows/integration.yml@master

  Push-images:
    needs: Integration
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get tag if exist
        run: echo "VERSION=$(git describe --contains || true)" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Building & pushing images
        id: build-images
        run: make images

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
