name: Building and Pushing Gems

on:
  push:
    tags:
      - '*'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  CI:
    uses: enspirit/talktome/.github/workflows/integration.yml@master

  Rubygem:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - name: Release Gem
        id: gem-push
        run: make gem.publish
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()

  Github-release:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - name: Build package
        run: make gem
        id: build-package

      - uses: ncipollo/release-action@v1
        id: create-release
        with:
          artifacts: "pkg/talktome*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
